version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stockey-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stockey
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  express:
    build: .  # 현재 디렉토리를 빌드 컨텍스트로 설정
    image: chaean/stockey-backend:latest  # 빌드된 이미지를 태그
    container_name: stockey-express
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: stockey
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: